# Generated by Django 5.0 on 2024-08-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=50)),
                ('numStudents', models.IntegerField()),
                ('deptAvg', models.IntegerField()),
                ('publications', models.TextField()),
                ('patents', models.TextField()),
                ('achievements', models.TextField()),
                ('awards', models.TextField()),
                ('alumniAchievements', models.TextField()),
                ('startups', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
