# Generated by Django 5.0 on 2024-08-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_report_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='achievements',
            field=models.TextField(verbose_name='Achievements'),
        ),
        migrations.AlterField(
            model_name='report',
            name='alumniAchievements',
            field=models.TextField(verbose_name='Alumni Achievements'),
        ),
        migrations.AlterField(
            model_name='report',
            name='awards',
            field=models.TextField(verbose_name='Awards'),
        ),
        migrations.AlterField(
            model_name='report',
            name='dept',
            field=models.CharField(max_length=50, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='report',
            name='deptAvg',
            field=models.IntegerField(verbose_name='Department Average'),
        ),
        migrations.AlterField(
            model_name='report',
            name='numStudents',
            field=models.IntegerField(verbose_name='No. Of Students'),
        ),
        migrations.AlterField(
            model_name='report',
            name='patents',
            field=models.TextField(verbose_name='Patents'),
        ),
        migrations.AlterField(
            model_name='report',
            name='publications',
            field=models.TextField(verbose_name='Publications'),
        ),
        migrations.AlterField(
            model_name='report',
            name='startups',
            field=models.TextField(verbose_name='Startups'),
        ),
    ]
