# Generated by Django 5.0 on 2024-08-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_alter_report_achievements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='deptAvg',
            field=models.IntegerField(verbose_name='Average'),
        ),
        migrations.AlterField(
            model_name='report',
            name='numStudents',
            field=models.IntegerField(verbose_name='Students'),
        ),
    ]
